apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole
  namespace: default
spec:
  encryptedData:
    pihole-webpassword: AgBTJxlLL7YlXEKUaP9zg0/2oRD4IzkW66/c4x1hHuxO3tJvftQHLVcDREqBfc9SLA6/W97irxtDkxdbGYofhuZwAt88NaS73MlFefayVTzG+rDG1swiuysoFfnCDJN65R4mHt1PkaDk+vFYFflTjzWiy69ztxw+NxDZD680O0T+KZd2o4rps4XMOkhGQCHd1nJ7haXRw7R5N/4eYSJy6Mn/aVD/Xcj4SRMoa5GPnL7rFzTM5iQK3L5wefWk7XcZJqJs/cF3ziyQ7hz5iCp50qfBxEvszINvv82BMruGCprahGGzL3JeuBwC9yWuroZgXLcEfxnNW4yrpC4E2YcLj93I4QqA1TWBar/5wZo3mv836bN64KSQ5jj+Gg191HeydNFVH2t6IjRKVc0ffCAZid1r4XEk/xBnTzBmVmNQa24c0eF/aTlMbPz6QljvrvbSmJ6OxQBY1cy4WEbnOT+wKuMQOptpS52xbnRmcFv+ZgYK5T3KUhrSe90fGndZmWUsy0ezAlnQAaZG7a05BUL+blDPCuSpf0j69nO1oB+Ma0vHs5CNfZuXw7e12L52jMvRwVj6/kQUn4+NhH2FDvO2a6VuctXzTSHCiQS8SocEWwmuxieisP4KnssCH6Gg+pTovD0EBk35NIJFTYCoBRRvu3Ul0WMbiczyEDyvYHQLdoQ8r0JxA4Lq9cgqLPEUfvYAnD4C/UM+sC0oF6VYFg==
  template:
    metadata:
      creationTimestamp: null
      name: pihole
      namespace: default
status: {}

