apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.7
apiServer:
  certSANs:
  - "vip01"
controlPlaneEndpoint: "vip01:6443"
networking:
  podSubnet: 10.11.0.0/16
  serviceSubnet: 10.96.0.0/12